FakeSDK.MVCSample/FakeSDK.MVCSample/Models/ErrorViewModel.cs
using System;

namespace FakeSDK.MVCSample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FakeSDK.MVCSample/FakeSDK.MVCSample/ViewModels/ConfirmPaymentViewModel.cs
namespace FakeSDK.MVCSample.ViewModels
{
    public class ConfirmPaymentViewModel
    {
        public string Md { get; set; }
        public string PaReq { get; set; }
        public string TermUrl { get; set; }
    }
}

FakeSDK.MVCSample/FakeSDK.MVCSample/ViewModels/CreatePaymentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using FakeSDK.Models;

namespace FakeSDK.MVCSample.ViewModels
{
    public class CreatePaymentViewModel
    {
        [Required]
        [Range(0.0, 999_999.00, ErrorMessage = "Amount must be a valid number")]
        public double Amount { get; set; }

        [Required]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "Should be valid currency code")]
        public string Currency { get; set; }

        [Required]
        [StringLength(2, MinimumLength = 2, ErrorMessage = "Should be valid country code")]
        public string Country { get; set; }

        [Required]
        public string CardNumber { get; set; }

        [Required]
        public string CardHolder { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime CardExpiryDate { get; set; }

        [Required]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "Should be valid CVV code")]
        public string CVV { get; set; }

        [Required]
        public string Md { get; set; }

        public CreatePaymentRequest ToRequest()
        {
            return new CreatePaymentRequest
            {
                Amount = (uint) Amount * 100,
                CardNumber = CardNumber,
                Country = Country,
                Currency = Currency,
                CardHolder = CardHolder,
                CardExpiryDate = CardExpiryDate,
                CVV = CVV,
                OrderId = Guid.NewGuid().ToString()
            };
        }
    }
}

FakeSDK.MVCSample/FakeSDK.MVCSample/Controllers/HomeController.cs
using System.Diagnostics;
using FakeSDK.MVCSample.Models;
using Microsoft.AspNetCore.Mvc;

namespace FakeSDK.MVCSample.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

FakeSDK.MVCSample/FakeSDK.MVCSample/Controllers/PaymentController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using FakeSDK.Models;
using FakeSDK.MVCSample.ViewModels;
using FakeSDK.Services;
using Microsoft.AspNetCore.Mvc;

namespace FakeSDK.MVCSample.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IFakePaymentService _fakePaymentService;

        public PaymentController(IFakePaymentServiceBuilder serviceBuilder)
        {
            _fakePaymentService = serviceBuilder.Build();
        }

        // GET
        public IActionResult Create()
        {
            var demoRequest = new CreatePaymentViewModel
            {
                Amount = 12312,
                CardHolder = "TEST TESTER",
                CardExpiryDate = DateTime.ParseExact("1123", "MMyy", null),
                CardNumber = "4111111111111111",
                Country = "CY",
                Currency = "USD",
                CVV = "111",
                Md = "testorder-1"
            };
            return View(demoRequest);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePaymentViewModel request)
        {
            if(!ModelState.IsValid)
            {
                return View(request);
            }

            var response = await _fakePaymentService.CreatePaymentAsync(request.ToRequest(), CancellationToken.None);

            return RedirectToAction("Secure", new {request.Md, response.PaReq, response.TransactionId});
        }

        // GET
        public IActionResult Secure(string md, string paReq, string transactionId)
        {
            var absoluteCallbackUrl = $"http://localhost:5000/payment/secured/{transactionId}/";
            var demoRequest = new ConfirmPaymentViewModel
            {
                PaReq = paReq,
                Md = md,
                TermUrl = absoluteCallbackUrl
            };
            return View(demoRequest);
        }

        [HttpGet]
        public async Task<IActionResult> Secured(string id, [FromQuery]string md, [FromQuery]string paRes)
        {
            var demoRequest = new ConfirmPaymentRequest
            {
                PaRes = paRes,
                TransactionId = Guid.Parse(id)
            };
            var res = await _fakePaymentService.ConfirmPaymentAsync(demoRequest, CancellationToken.None);
            return RedirectToAction("Status", new {id});
        }

        public async Task<IActionResult> Status(Guid id)
        {
            var res = await _fakePaymentService.GetPaymentStatusAsync(id, CancellationToken.None);
            return View(res.Result);
        }
    }
}

FakeSDK.MVCSample/FakeSDK.MVCSample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div style="">
        <h1 class="display-4">Welcome to Fake Payment demo client</h1>
        <a class="button-simple" asp-controller="Payment" asp-action="Create">Try Demo</a>
    </div>
</div>

FakeSDK.MVCSample/FakeSDK.MVCSample/Views/Payment/Create.cshtml
@model FakeSDK.MVCSample.ViewModels.CreatePaymentViewModel

@{
    ViewData["Title"] = "Payment";
    Layout = "_Layout";
}

<form method="post" enctype="multipart/form-data" asp-controller="Payment" asp-action="Create">
    <table>
        <tr>
            <td>
                <label asp-for="Currency"></label>
            </td>
            <td>
                <input asp-for="Currency"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Country"></label>
            </td>
            <td>
                <input asp-for="Country"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Md"></label>
            </td>
            <td>
                <input asp-for="Md"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="CardNumber"></label>
            </td>
            <td>
                <input asp-for="CardNumber"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="CardHolder"></label>
            </td>
            <td>
                <input asp-for="CardHolder"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="CardExpiryDate"></label>
            </td>
            <td>
                <input asp-for="CardExpiryDate"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="CVV"></label>
            </td>
            <td>
                <input asp-for="CVV"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Amount"></label>
            </td>
            <td>
                <input asp-for="Amount"/><br/>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Submit"/>
            </td>
        </tr>
    </table>
</form>

FakeSDK.MVCSample/FakeSDK.MVCSample/Views/Payment/Secure.cshtml
@model FakeSDK.MVCSample.ViewModels.ConfirmPaymentViewModel

@{
    ViewData["Title"] = "Payment";
    Layout = "_Layout";
}

<form action="http://dumdumpay.site/secure/" method="POST">
    <table>
        <tr>
            <td>
                <label asp-for="Md"></label>
            </td>
            <td>
                <input asp-for="Md"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="PaReq"></label>
            </td>
            <td>
                <input asp-for="PaReq"/><br/>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="TermUrl"></label>
            </td>
            <td>
                <input asp-for="TermUrl"/><br/>
            </td>
        </tr>
    </table>
    <input type="submit" title="Submit"/>
</form>

FakeSDK.MVCSample/FakeSDK.MVCSample/Views/Payment/Status.cshtml
@model FakeSDK.Models.PaymentInfo;

@{
    ViewData["Title"] = "Payment";
    Layout = "_Layout";
}
<table>
    <tr>
        <td>
            <label asp-for="TransactionId" disabled></label>
        </td>
        <td>
            <input asp-for="TransactionId" disabled/><br/>
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Status" disabled></label>
        </td>
        <td>
            <input asp-for="Status" disabled/><br/>
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Amount" disabled></label>
        </td>
        <td>
            <input asp-for="Amount" disabled/><br/>
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Currency" disabled></label>
        </td>
        <td>
            <input asp-for="Currency" disabled/><br/>
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="OrderId" disabled></label>
        </td>
        <td>
            <input asp-for="OrderId" disabled/><br/>
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="LastFourDigits" disabled></label>
        </td>
        <td>
            <input asp-for="LastFourDigits" disabled/><br/>
        </td>
    </tr>
</table>

FakeSDK.MVCSample/FakeSDK.MVCSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FakeSDK.MVCSample</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FakeSDK.MVCSample</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Create">Demo Payment</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - FakeSDK.MVCSample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>